### ISSUE TITLE
crime_level function

### ISSUE THREAD

**Issue by ninoyao** [dsi-principles-prog/midterm-ninoyao#1]
Base on the histogram of the crime rate, we can find that the distribution of crime rate is skewed in our dataset.

In the real world, people do not usually know the crime rate distribution in their city. In other words, they do not know how high the crime rate is dangerous in their area.

For example, a 30% crime rate might be relatively low in Nashville but very high in Boston. If we categorize crime rates into different levels, we could understand how crime rates affect our housing value better. 

For a better understanding of the crime rate, I will cut the crime rates into different levels.I want to categorize crime rates into "low" ,"median", "high" by using the median and 3rd quartile. 

crime rates below median are "low"
crime rates between the median and 3rd quartile are "median"
crime rates higher than 3rd quartile are "high"

The output should be "character" with unique values "low", "median" and "high".

**Comment by aliccee** [comment]
crime_level <- function(df) {
  df %>% 
    mutate(crim_level = case_when(
      crim <- 0.09 ~"low",
      crim <- 3.7 ~"median",
      TRUE ~"high"
    ))
}

**Comment by aliccee** [comment]
crime_level <- function(df) {
 df %>%
 mutate(crim_level = case_when(
 crim <= 0.09 ~"low",
 crim <= 3.7 ~"median",
 TRUE ~"high"
))
}
